### ISSUE TITLE
TriangularArbitrageBot

### ISSUE THREAD

**Issue by jhalstead3** [ericjang/cryptocurrency_arbitrage#6]
I figure with the last updates being 3 years ago, and all of your other contributions, you've moved on. Just wondering if you had completed the TriangularArbitrageBot portion? I got balances working on another exchange, but when trying to run main_tri_backtest i get an AttributeError: 'Broker' object has no attribute 'rates' when it calls Broker.get_highest_bid.  Maybe I've just run out of brain power for the night, but I can't seem to track down where this attribute is supposed to be set from or what format it's expecting. I'm assuming my exchange isn't returning something right, but at a loss how to fix it at the moment.

**Comment by kelvinau** [comment]
@jhalstead3 I did implement a triangular arbitrage bot here https://github.com/kelvinau/crypto-arbitrage
But the fee is quite high on the exchanges. You may not earn much on that.

**Comment by jhalstead3** [comment]
@kelvinau, I got a few more steps into the process since my last comment. I may have just caused more problems for myself than I fixed, but I'll gladly take a look at yours. My biggest problem so far has been determining round trip paths. I've been using this as a way to learn Python, so i'm not too worried about profitability right now. Thanks again.
